name: Deployment
env:
  NAME: 'Snyk Demo'

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Print name
        run: echo "Hello $NAME"
      - name: Print certificate
        run: echo "$ { secrets.ALBYNODE }  "
    # deployment:
    #   environment: 
    #     name: github-pages