name: Deployment
env:
  NAME: 'Snyk Demo'

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Print name
        run: echo "Hello $NAME"
      # - name: Print secret
      #   run: echo "$ {{ secrets.ALBYNODE }}  " | base64 --decode
        env: # Or as an environment variable
          super_secret: ${{ secrets.ALBYNODE }}
        run: |
          echo $super_secret $NAME
    # deployment:
    #   environment: 
    #     name: github-pages